# Generated by Django 3.1.6 on 2021-02-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_category',
            field=models.CharField(blank=True, choices=[('AS/FX', 'Fixed Asset'), ('AS/CR', 'Current Asset')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_description',
            field=models.CharField(blank=True, default='a new account', max_length=255),
        ),
    ]
